### ISSUE TITLE
You may also like csvkit

### ISSUE THREAD

**Issue by timwis** [caseypt/GeoJSON.js#21]
Hey @caseypt! Not an issue or anything, just wanted to make you aware of csvkit's [csvjoin](http://csvkit.readthedocs.org/en/540/scripts/csvjson.html) utility. It lets you convert a CSV file to GeoJSON on the command line similar to how GeoJSON.js lets you do it with a javascript array within javascript. Just thought you'd find it interesting. Hope all is well.

**Comment by caseypt** [comment]
Thanks for the tip, @timwis. csvkit is great. I hope things are good with you as well.
